Wazo 2909 python3
wazo-platform/wazo-provd-cli pull request #12
Opened 2022-11-03 15:04 UTC by sopelj

2022-11-15 21:40 UTC, bloom1 commented on tox.ini
> +envlist = poy37, black, flake8, linters
`poy37` is surely a typo :smile_cat:

2022-11-15 21:56 UTC, bloom1 commented on tox.ini
> +envlist = poy37, black, flake8, linters
Fixed :+1:

2022-11-15 22:18 UTC, bloom1 requested changes
I have an issue with the argument parser when trying `wazo-provd-cli --help`: 
```shell
Traceback (most recent call last):
  File "/usr/bin/wazo-provd-cli", line 3, in <module>
    from wazo_provd_cli import cli
  File "/usr/lib/python3/dist-packages/wazo_provd_cli/cli.py", line 56, in <module>
    opts, args = parser.parse_known_args()
  File "/usr/lib/python3.7/argparse.py", line 1797, in parse_known_args
    self.error(str(err))
  File "/usr/lib/python3.7/argparse.py", line 2508, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib/python3.7/argparse.py", line 2478, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib/python3.7/argparse.py", line 2444, in format_usage
    return formatter.format_help()
  File "/usr/lib/python3.7/argparse.py", line 293, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.7/argparse.py", line 224, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 224, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.7/argparse.py", line 310, in _format_usage
    usage = usage % dict(prog=self._prog)
ValueError: unsupported format character 'p' (0x70) at index 8
```

2022-11-16 14:13 UTC, sopelj commented
> I have an issue with the argument parser when trying `wazo-provd-cli --help`:
> 
> ```shell
> Traceback (most recent call last):
>   File "/usr/bin/wazo-provd-cli", line 3, in <module>
>     from wazo_provd_cli import cli
>   File "/usr/lib/python3/dist-packages/wazo_provd_cli/cli.py", line 56, in <module>
>     opts, args = parser.parse_known_args()
>   File "/usr/lib/python3.7/argparse.py", line 1797, in parse_known_args
>     self.error(str(err))
>   File "/usr/lib/python3.7/argparse.py", line 2508, in error
>     self.print_usage(_sys.stderr)
>   File "/usr/lib/python3.7/argparse.py", line 2478, in print_usage
>     self._print_message(self.format_usage(), file)
>   File "/usr/lib/python3.7/argparse.py", line 2444, in format_usage
>     return formatter.format_help()
>   File "/usr/lib/python3.7/argparse.py", line 293, in format_help
>     help = self._root_section.format_help()
>   File "/usr/lib/python3.7/argparse.py", line 224, in format_help
>     item_help = join([func(*args) for func, args in self.items])
>   File "/usr/lib/python3.7/argparse.py", line 224, in <listcomp>
>     item_help = join([func(*args) for func, args in self.items])
>   File "/usr/lib/python3.7/argparse.py", line 310, in _format_usage
>     usage = usage % dict(prog=self._prog)
> ValueError: unsupported format character 'p' (0x70) at index 8
> ```

Wow, of all the options to have forgotten to test... sorry. It's fixed.

2022-11-17 20:42 UTC, bloom1 approved these changes

2022-11-17 20:45 UTC, merged